### PR TITLE
allow to override default auth prefix 'Bearer' with an optional option --auth-prefix=XXX #8

### PR DESCRIPTION
**Pull request by hoatle**
and should not require to have colon character #3

NOTE: waiting for https://github.com/jkbrzt/httpie/issues/378

### CODE REVIEW

**Comment by shtouff** [comment]
+1 

djangorestframework-jwt uses 'JWT' prefix by default, not 'Bearer'.

**Comment by hoatle** [comment]
@shtouff FYI, v0.2.0 has just been released with support for changing jwt prefix: https://github.com/teracyhq/httpie-jwt-auth/blob/master/CHANGELOG.md#020-2016-01-29

**Comment by shtouff** [comment]
@hoatle Thanks for your change. 

However this is not python3 compliant. I'll send you a PR soon.

**Comment by hoatle** [comment]
Great, can't wait for your PR :)

**Comment by hoatle** [comment]
closed, seems that this is not yet supported by httpie

**Pull request closed without merging**
